export default {
  state: {
    data: [
      {
        name: "Calendar",
        image: "images/calendar.jpg",
        category: "UI Design",
        link: "/",
        tag: "ui",
      },
      {
        name: "Mobile App",
        image: "images/flutter_ad.jpg",
        category: "Mobile App",
        link: "ajax/portfolio-ajax-project-2.html",
        tag: "flutter-dev",
      },
      {
        name: "Laraval 'n' Vue",
        image: "images/LaravelVue.jpg",
        category: "Websites",
        link: "ajax/portfolio-ajax-project-3.html",
        tag: "web-dev",
      },
      {
        name: "Vimeo",
        image: "images/project-5.jpg",
        category: "Category",
        link: "ajax/portfolio-ajax-project-4.html",
        tag: "vimeo",
      },
      {
        name: "Tracker App",
        image: "images/tracker.jpg",
        category: "UI Design",
        link: "ajax/portfolio-ajax-project-1.html",
        tag: "ui",
      },
      {
        name: "Flutter",
        image: "images/flutter_ad2.jpg",
        category: "Category",
        link: "ajax/portfolio-ajax-project-2.html",
        tag: "flutter-dev",
      },
      {
        name: "Web dev",
        image: "images/project-4.jpg",
        category: "Web dev",
        link: "ajax/portfolio-ajax-project-3.html",
        tag: "web-dev",
      },
      {
        name: "Vimeo",
        image: "images/project-5.jpg",
        category: "Category",
        link: "ajax/portfolio-ajax-project-4.html",
        tag: "vimeo",
      },
      {
        name: "UI Design",
        image: "images/project-2.jpg",
        category: "Category",
        link: "ajax/portfolio-ajax-project-1.html",
        tag: "ui",
      },
      {
        name: "Flutter dev",
        image: "images/project-3.jpg",
        category: "Category",
        link: "ajax/portfolio-ajax-project-2.html",
        tag: "flutter-dev",
      },
      {
        name: "Web dev",
        image: "images/project-4.jpg",
        category: "Category",
        link: "ajax/portfolio-ajax-project-3.html",
        tag: "web-dev",
      },
      {
        name: "Vimeo",
        image: "images/project-5.jpg",
        category: "Category",
        link: "ajax/portfolio-ajax-project-4.html",
        tag: "vimeo",
      },
    ],
  },
  getters: {},
  mutations: {},
  actions: {},
};
